version: "3.1"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  dbMysql:
    image: mariadb:10.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:  
      MYSQL_ROOT_PASSWORD: "123"  
      MYSQL_DATABASE: hw9up
    volumes:
      - './_mysql/:/docker-entrypoint-initdb.d'
